updated new code

diff --git a/.github/workflows/main_demotestspringboot.yml b/.github/workflows/main_demotestspringboot.yml
--- a/.github/workflows/main_demotestspringboot.yml
+++ b/.github/workflows/main_demotestspringboot.yml
@@ -42,19 +42,47 @@ jobs:
       - name: Azure Login
         run: az login
         env:
-            AZURE_SERVICE_PRINCIPAL_CLIENT_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
-            AZURE_SERVICE_PRINCIPAL_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
-            AZURE_SERVICE_PRINCIPAL_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
+          AZURE_SERVICE_PRINCIPAL_CLIENT_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
+          AZURE_SERVICE_PRINCIPAL_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
+          AZURE_SERVICE_PRINCIPAL_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
 
-  
-      - name: 'Run Azure Functions Action'
+      - name: Upload JAR to Azure Storage
+        run: |
+          az storage blob upload \
+            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
+            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
+            --container-name ${{ secrets.AZURE_STORAGE_CONTAINER }} \
+            --name my-app-folder/my-app.jar \
+            --file target/my-app.jar
+
+      - name: Download JAR from Azure Storage
+        run: |
+          az storage blob download \
+            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
+            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
+            --container-name ${{ secrets.AZURE_STORAGE_CONTAINER }} \
+            --name my-app-folder/my-app.jar \
+            --file my-app/my-app.jar
+
+      - name: List downloaded files
+        run: ls -al my-app
+
+      - name: Verify JAR file
+        run: |
+          if [ ! -f "my-app/my-app.jar" ]; then
+            echo "JAR file not found!"
+            exit 1
+          fi
+
+      - name: Run Azure Functions Action
         uses: Azure/functions-action@v1
         id: fa
         with:
           app-name: 'demofunlinapp'
-          package: '${{ env.POM_XML_DIRECTORY }}' # if there are multiple function apps in same project, then this path will be like './${{ env.POM_XML_DIRECTORY }}/target/azure-functions/${{ env.POM_FUNCTIONAPP_NAME }'
+          package: 'my-app' # Specify the folder containing the downloaded JAR file
           publish-profile: ${{ secrets.PUBLISH_PROFILE }}
           respect-pom-xml: true
+
 
         
   #     - name: Build with Maven and Run SonarCloud analysis
