updated new code

diff --git a/.github/workflows/main_demotestspringboot.yml b/.github/workflows/main_demotestspringboot.yml
--- a/.github/workflows/main_demotestspringboot.yml
+++ b/.github/workflows/main_demotestspringboot.yml
@@ -1,4 +1,4 @@
-name: Build and deploy JAR app to Azure Function App - demofunlinapp
+name: Build and deploy JAR app to Azure Function App - demolinfunapp
 
 on:
   push:
@@ -11,7 +11,6 @@ on:
 
 env:
   AZURE_FUNCTIONAPP_NAME: demofunlinapp # set this to your function app name on Azure
-  PACKAGE_DIRECTORY: '.'
   JAVA_VERSION: '17' # set this to the java version to use
 
 jobs:
@@ -39,8 +38,8 @@ jobs:
           TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
-      - name: Rename JAR file
-        run: mv target/*.jar target/my-app.jar
+      - name: Check target directory after build
+        run: ls -R target
 
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v3
@@ -59,23 +58,25 @@ jobs:
         uses: actions/download-artifact@v3
         with:
           name: java-app
-          path: '${{ github.workspace }}/target/*.jar'
+      
+      - name: Check target directory after download
+        run: ls -R target
 
-      - name: Azure Login
-        run: az login
-        env:
-            AZURE_SERVICE_PRINCIPAL_CLIENT_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
-            AZURE_SERVICE_PRINCIPAL_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
-            AZURE_SERVICE_PRINCIPAL_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
+      - name: Find JAR file
+        id: locate-jar
+        run: echo "JAR_FILE=$(ls target/*.jar)" >> $GITHUB_ENV
+
+      - name: Verify JAR file exists
+        run: if [ ! -f "${{ env.JAR_FILE }}" ]; then echo "JAR file not found!"; exit 1; fi
+
+      - name: Verify working directory
+        run: ls -R
 
       - name: Run Azure Functions Action
         id: deploy-to-functionapp
         uses: Azure/functions-action@v1
         with:
-          app-name: 'demofunlinapp'
-          package: '${{env.PACKAGE_DIRECTORY}}'
+          app-name: 'demolinfunapp'
+          package: ${{ env.JAR_FILE }}
           respect-pom-xml: true
           publish-profile: ${{ secrets.PUBLISHPROFILE }}
-
-
-          
