updated new code

diff --git a/.github/workflows/main_demotestspringboot.yml b/.github/workflows/main_demotestspringboot.yml
--- a/.github/workflows/main_demotestspringboot.yml
+++ b/.github/workflows/main_demotestspringboot.yml
@@ -9,17 +9,10 @@ on:
       - 'pom.xml'
       - '.github/workflows/main_demotestspringboot.yml'
 
-# CONFIGURATION
-# For help, go to https://github.com/Azure/Actions
-#
-# 1. Set up the following secrets in your repository:
-#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
-#
-# 2. Change these variables for your configuration:
 env:
   AZURE_FUNCTIONAPP_NAME: 'demofunlinapp'   # set this to your function app name on Azure
   POM_XML_DIRECTORY: '.'                    # set this to the directory which contains pom.xml file
-  JAVA_VERSION: '17'                         # set this to the java version to use (e.g. '8', '11', '17')
+  JAVA_VERSION: '17'                        # set this to the java version to use (e.g. '8', '11', '17')
 
 jobs:
   build-and-deploy:
@@ -28,7 +21,7 @@ jobs:
       security-events: write
       actions: read
       contents: read
-    #environment: dev
+
     steps:
     - name: 'Checkout GitHub Action'
       uses: actions/checkout@v3
@@ -52,14 +45,43 @@ jobs:
         AZURE_SERVICE_PRINCIPAL_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
         AZURE_SERVICE_PRINCIPAL_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
 
-    - name: 'Run Azure Functions Action'
+    - name: Upload JAR to Azure Storage
+      run: |
+        az storage blob upload \
+          --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
+          --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
+          --container-name ${{ secrets.AZURE_STORAGE_CONTAINER }} \
+          --name my-app-folder/my-app.jar \
+          --file target/my-app.jar
+
+    - name: Download JAR from Azure Storage
+      run: |
+        az storage blob download \
+          --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
+          --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
+          --container-name ${{ secrets.AZURE_STORAGE_CONTAINER }} \
+          --name my-app-folder/my-app.jar \
+          --file my-app/my-app.jar
+
+    - name: List downloaded files
+      run: ls -al my-app
+
+    - name: Verify JAR file
+      run: |
+        if [ ! -f "my-app/my-app.jar" ]; then
+          echo "JAR file not found!"
+          exit 1
+        fi
+
+    - name: Run Azure Functions Action
       uses: Azure/functions-action@v1
       id: fa
       with:
         app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
-        package: '${{ env.POM_XML_DIRECTORY }}' # if there are multiple function apps in same project, then this path will be like './${{ env.POM_XML_DIRECTORY }}/target/azure-functions/${{ env.POM_FUNCTIONAPP_NAME }'
+        package: 'my-app/my-app.jar'
         publish-profile: ${{ secrets.PUBLISH_PROFILE }}
         respect-pom-xml: true
+
 
 # For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
 
